version: 2.1
orbs:
  clojure-leiningen:
    executors:
      leiningen:
        docker:
          - image: circleci/clojure:lein-2.8.1
        environment:
          LEIN_ROOT: "true"
          JVM_OPTS: -Xmx3200m
        working_directory: ~/repo
    jobs:
      lein-test:
        executor: leiningen
        steps:
          - checkout
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "project.clj" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
          - run: lein test
          - save_cache:
              paths:
                - ~/.m2
              key: v1-dependencies-{{ checksum "project.clj" }}
workflows:
  test:
    jobs:
      - clojure-leiningen/lein-test
